### ISSUE TITLE
ModelItem Activation for element at ControlTemplate

### ISSUE THREAD

**Issue by HClausing** [microsoft/xaml-designer-extensibility#33]
Hi all.

One doublt: Is possible to activate an ModelItem for element at ControlTemplate's Control ?

Ex: I've created a new class inheriting from Control. On its ControlTemplate VisualTree there's a TabControl. On XAML Designer I can't change the Selected tab.

There's a image illustrating this situation:

![image](https://user-images.githubusercontent.com/15158923/94809423-f42f1180-03c8-11eb-97ea-a5df3b9c6523.png)

Thanks.

**Comment by debonte** [comment]
Can you provide more detailed repro steps for this issue?

Selection of a WPF TabItem or its content should cause the TabItem to be become the selected tab.

**Comment by HClausing** [comment]
Hi,

Actualy this element is not a TabControl (on root). There a custom control caled "StartMenu" with a TabControl on its ControlTemplate.

But, by this way, I can't change the selected Tab using on XAML designer. I was thinking about to know if there's anything on extensibility to create this behavior.

Another way is to modify the StartMenu control to inherits the TabControl. (so much easier, by the way). 

Thanks.

**Comment by debonte** [comment]
Ok, I understand now. The problem is that the TabItems and their content are not in the designer's editing scope. If you look in the Document Outline pane, you'll see that the current scope is the Window. Elements within the templates of any templated controls used in the Window are not shown -- which is why the TabControl, TabItem, and tab contents are not shown and are also not selectable.

If you want to select or edit elements within a template in the XAML designer, you need to scope into the template via one of the template editing commands. For example, in your case you could right-click on the StartMenu element and select Edit Template > Edit Current.

At that point the scope should change to the template and you'll see the TabControl, TabItem, and tab contents in the Document Outline. You'll also be able to change tabs via selection.

Does this address your issue? If you want to be able to select TabItems without scoping into the StartMenu template, I'd be curious to know why and what your next action in the designer would be. For example, if your intent is to edit / set properties on elements within the newly selected TabItem, you won't be able to do that until you scope into the template.

**Comment by HClausing** [comment]
Hello @debonte .

Thanks for the explanation!

You are right. So, I think the next step is modify the StartMenu control to Inherits from TabControl, to get the designer tools working as desired.

By this behavior, I'm planning to prepare the controlTemplate to wokr with at least one fixed TabItem, and another colletion in XAML. I was reading about the CompositeCollection class, and I think its perfect for my work. 

Something like this:

<Style TargetType="{x:Type efcore:StartMenu}"  />
<Setter Property="ItemsSource">
            <Setter.Value>
                <CompositeCollection>
                    
                    <TabItem x:Name="FixeStartItem"  />
                    .....
                    <CollectionContainer />

I'll update this topic to say if it worked or not.

Thanks again!
